=== markussundstrom/synthboss/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "synth-definition",
    "title": "Synthdef",
    "description": "Definition of a synth's parameters",
    "type": "object",
    "properties": {
        "manufacturer": {
            "type": "string"
        },
        "model": {
            "type": "string"
        },
        "shortname": {
            "type": "string",
            "pattern": "^[a-z0-9]{3,}$"
        },
        "parts": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "channel": {
                        "type": "integer"
                    },
                    "channeloffset": {
                        "type": "integer"
                    },
                    "messageformat": {
                        "type": "string"
                    },
                    "sections": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "parameters": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "parameternumber": {
                                                "type": "integer"
                                            },
                                            "class": {
                                                "type": "string",
                                                "enum": [
                                                    "range",
                                                    "toggle",
                                                    "select"
                                                ]
                                            }
                                        },
                                        "allOf": [
                                            {
                                                "if": {
                                                    "properties": {
                                                        "class": {
                                                            "const": "range"
                                                        }
                                                    }
                                                },
                                                "then": {
                                                    "properties": {
                                                        "max": {
                                                            "type": "integer"
                                                        },
                                                        "min": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            },
                                            {
                                                "if": {
                                                    "properties": {
                                                        "key": {
                                                            "const": "toggle"
                                                        }
                                                    }
                                                },
                                                "then": {
                                                    "properties": {
                                                        "on": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            },
                                            {
                                                "if": {
                                                    "properties": {
                                                        "key": {
                                                            "const": "select"
                                                        }
                                                    }
                                                },
                                                "then": {
                                                    "properties": {
                                                        "choices": {
                                                            "type": "array",
                                                            "items": {
                                                                "type": "object",
                                                                "properties": {
                                                                    "name": {
                                                                        "type": "string"
                                                                    },
                                                                    "optionvalue": {
                                                                        "type": "integer"
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        ]
                                            
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "required": [ "manufacturer", "model", "shortname" ]
}

=== markussundstrom/synthboss/devices/mks7.json
{
    "manufacturer": "Roland",
    "model": "MKS7",
    "shortname": "mks7",
    "parts": [
        {
            "name": "Bass",
            "sections": [
            ]
        },
        {
            "name": "Melody",
            "sections": [
                {
                    "name": "DCO",
                    "parameters": [
                        {
                            "name": "Range",
                            "class": "select",
                            "choices": [
                                {
                                    "name": "2'"
                                },
                                {
                                    "name": "4'"
                                },
                                {
                                    "name": "8'"
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "Filter",
                    "parameters": [
                        {
                            "name": "Cutoff",
                            "class": "range",
                            "min": 0,
                            "max": 127
                        },
                        {
                            "name": "Resonance",
                            "class": "range",
                            "min": 0,
                            "max": 127
                        }
                    ]
                }
            ]
        }
    ]
}

=== markussundstrom/synthboss/mks7.json
{
    "manufacturer": "Roland",
    "model": "MKS-7",
    "shortname": "mks7",
    "parts": [
        {
            "name": "Bass",
            "sections": [
                {
                    "name": "DCO",
                    "parameters": [
                        {
                            "name": "Range",
                            "class": "select",
                            "value": 0,
                            "choices": [
                                {
                                    "name": "8'",
                                    "value": 0
                                },
                                {
                                    "name": "16'",
                                    "value": 1
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "VCF",
                    "parameters": [
                        {
                            "name": "HPF",
                            "class": "toggle",
                            "value": 0
                        },
                        {
                            "name": "Cutoff",
                            "class": "range",
                            "value": 0,
                            "max": 127,
                            "min": 0
                        },
                        {
                            "name": "Resonance",
                            "class": "range",
                            "value": 0,
                            "max": 127,
                            "min": 0
                        }
                    ]
                }
            ]
        }
    ]
}
